---
title: "Aproximaci칩n a las Pol칤ticas P칰blicas desde los datos"
---

## Descripci칩n del curso

El concepto de pol칤ticas basadas en evidencia adquiere cada vez m치s relevancia en distintos sectores dedicados a el an치lisis y dise침o de pol칤ticas p칰blicas, por lo que se hace necesario contar con profesionales preparados para estos efectos.

La era digital ha producido una explosi칩n de datos conductuales y relacionales de distinta naturaleza com칰nmente denominados big data. La ciencia social computacional (CSC) utiliza herramientas computacionales para procesar, analizar, visualizar y modelar estos datos. Este curso introduce a 2 치reas de inter칠s para la CSC: **1) la extracci칩n y manipulaci칩n de bases de datos** y **2) t칠cnicas aplicadas al an치lisis de datos geogr치ficos (GD), redes sociales (SNA) y el procesamiento del lenguaje natural (NLP)**.

Las clases estar치n programas de la siguiente manera:

|          |       Fecha        |    Horario    | Contenidos                                         |                           Materiales                            |                                 Laboratorios.                                  |
|----------|:------------------:|:-------------:|----------------------------------------------------|:---------------------------------------------------------------:|:------------------------------------------------------------------------------:|
| Sesi칩n 1 | Viernes 12/05/2023 | 18:30 - 21:45 | Introducci칩n a las CSC para pol칤ticas p칰blcas      | [游둰勇끃(class/class-1.html "Clase 1"){aria-label="Clase 1 slides"} |                                                                                |
| Sesi칩n 2 | Viernes 26/05/2023 | 18:30 - 21:45 | Introducci칩n a las CSC para pol칤ticas p칰blcas      | [游둰勇끃(class/class-1.html "Clase 1"){aria-label="Clase 1 slides"} |                                                                                |
| Sesi칩n 3 | Viernes 09/06/2023 | 18:30 - 21:45 | Fundamentos de la estad칤stica para las CSC         | [游둰勇끃(class/class-2.html "Clase 2"){aria-label="Clase 2 slides"} | [游닄](labs/lab-c2.html "Laboratorio clase 2"){aria-label="Laboratorio clase 2"} |
| Sesi칩n 4 | S치bado 10/06/2023  | 09:00 - 12:15 | Extracci칩n autom치tica de texto: Webscraping y APIs | [游둰勇끃(class/class-3.html "Clase 3"){aria-label="Clase 3 slides"} | [游닄](labs/lab-c3.html "Laboratorio clase 3"){aria-label="Laboratorio clase 3"} |
| Sesi칩n 5 | Viernes 30/06/2023 | 18:30 - 21:45 | Introducci칩n al an치lisis de redes sociales         |                                                                 |                                                                                |
| Sesi칩n 6 | Viernes 14/07/2023 | 18:30 - 21:45 | An치lisis de datos geogr치ficos                      |                                                                 |                                                                                |
| Sesi칩n 7 | Viernes 04/08/2023 | 18:30 - 21:45 | An치lisis automatizado de texto                     |                                                                 |                                                                                |
| Sesi칩n 8 | S치bado 05/08/2023  | 09:00 - 12:15 | Presentaci칩n de trabajos finales                   |                                                                 |                                                                                |

## Objetivos de aprendizaje

Al terminar el curso, los estudiantes sabr치n:

1.  Identificar tipos de datos para distintas preguntas de investigaci칩n.

2.  Identificar ventajas y desventajas de distintos m칠todos emp칤ricos.

3.  Aplicar m칠todos de ciencia de datos utilizando an치lisis estad칤stico

Los puntos anteriores se realizar치n utilizando `R`, por lo que **los/as estudiantes profundizar치n su conocimiento de este lenguaje de programaci칩n**.

## Metodolog칤a del curso

El curso es pr치ctico por lo que tiene el prop칩sito de ense침ar a programar orientado proyectos, por lo que tendremos actividades:

-   **Interactivas**: los estudiantes deber치n programar an치lisis a partir de una pregunta/objetivo de investigaci칩n

-   **De an치lisis**: los estudiantes deber치n leer investigaciones en el 치rea y exponer a sus compa침eros los aspectos principales

-   **Aplicaci칩n**: los estudiantes deber치n aplicar alguna de las t칠cnicas vistas a una pregunta **relevante para las pol칤ticas p칰blicas**

## Evaluaciones

El curso tendr치 4 evaluaciones ponderadas y organizadas de la siguiente manera:

|                | Fecha Publicaci칩n |                                                      Fecha - Horario de entrega                                                       | Contenidos                          |                            Pautas                            |
|----------------|:-----------------:|:-------------------------------------------------------------------------------------------------------------------------------------:|-------------------------------------|:------------------------------------------------------------:|
| Tarea 1        |    30/05/2023     |                                                          25/06/2023 - 23:59                                                           | Propuesta proyecto de investigaci칩n |       [Click aqu칤](/exams/Tarea1.pdf "Pauta Tarea 1")        |
| Tarea 2        |    30/06/2023     |                                                          16/07/2023 - 23:59                                                           | Ajuste a la propuesta + metodolog칤a |       [Click aqu칤](/exams/Tarea2.pdf "Pauta Tarea 2")        |
| Proyecto       |    30/06/2023     |                                                      05/08/2023 - 18:30 a 21:45                                                       | Presentaci칩n de resultados          |      [Click aqu칤](/exams/Proyecto.pdf "Pauta Proyecto")      |
| Presentaciones |        \-         | [Link aqu칤](https://uccl0-my.sharepoint.com/:x:/g/personal/jdconejeros_uc_cl/Ed-gi54og-1MiaccCW2WG6EBdrPFG6ON3mvnrtvaCmP4Yw?e=k111Ew) | Presentaci칩n de art칤culos           | [Click aqu칤](/exams/Presentaciones.pdf "Pauta Presentaci칩n") |

**Todas las evaluaciones se deben enviar por correo al profesor Jos칠 Daniel Conejeros [jdconejeros\@uc.cl](jdconejeros@uc.cl) con copia a la ayudante Sof칤a Madariaga Alvarado [samadariaga\@uc.cl](samadariaga@uc.cl).**

## Integridad acad칠mica

*Como miembro de la comunidad de la Pontificia Universidad Cat칩lica de Chile, me comprometo a respetar los principios y normativas que la rigen. Asimismo, me comprometo a actuar con rectitud y honestidad en las relaciones con los dem치s integrantes de la comunidad y en la realizaci칩n de todo trabajo, particularmente en aquellas actividades vinculadas a la docencia, al aprendizaje y la creaci칩n, difusi칩n y transferencia del conocimiento. Adem치s, me comprometo a velar por la dignidad e integridad de las personas, evitando incurrir en y, rechazando, toda conducta abusiva de car치cter f칤sico, verbal, psicol칩gico y de violencia sexual. Del mismo modo, asumo el compromiso de cuidar los bienes de la Universidad*.

M치s detalles sobre la integridad acad칠mica UC aqu칤: <https://integridadacademica.uc.cl/>

## Contribuciones y agradecimientos

El contenido de este curso fue desarrollado y adaptado a partir del trabajo del Ph.D. [Naim Bro](https://naimbro.github.io/) Profesor asistente de la Universidad Adolfo Iba침ez y Ph.D. en Sociolog칤a de la universidad de Cambridge.

-   Puedes acceder al curso de referencia aqu칤: [Data policy](https://naimbro.github.io/programa_diplomado_2022.html)

El formato web de este curso fue desarrollado y adaptado a partir del trabajo de la Ph.D. [Mine 칂etinkaya-Rundel](https://mine-cr.com/) Profesora y Directora de Estudios de Grado del Departamento de Ciencias Estad칤sticas de la Universidad de Duke.

-   Puedes acceder al curso de referencia aqu칤: [STA 210](https://sta210-s22.github.io/website/)
